kind: pipeline
type: exec
name: deploy2nomad
workspace:
  path: /drone/src
steps:
- name: Deploy
  environment:
    SERVICE_NAME:
      from_secret: SERVICE_NAME
    APPLICATION_NAME:
      from_secret: APPLICATION_NAME
    SERVICE_VERSION:
      from_secret: SERVICE_VERSION
    SERVICE_PORT:
      from_secret: SERVICE_PORT
    NOMAD_IP:
      from_secret: NOMAD_IP
  commands:
  - pwd
  - export NOMAD_ADDR="http://$NOMAD_IP:4646"
  - j2 /drone/src/srv-template.nomad > $SERVICE_NAME-$APPLICATION_NAME.nomad
  - nomad job validate $SERVICE_NAME-$APPLICATION_NAME.nomad
  - nomad job plan $SERVICE_NAME-$APPLICATION_NAME.nomad
  - nomad job run $SERVICE_NAME-$APPLICATION_NAME.nomad
---
# https://cogarius.medium.com/1-3-complete-guide-to-ci-cd-pipelines-with-drone-io-a53daaf28cf6
kind: pipeline
type: docker
name: notification

steps:

 - name: notification
   image: appleboy/drone-telegram
   settings:
     token:
       from_secret: TELEGRAM_TOKEN
     to: 
       from_secret: TELEGRAM_ID
     message: >
       📝 {{repo.name}} / {{commit.branch}} - {{commit.message}}
       {{#success build.status}}
         ✅ succeeded  for 👷‍♂️ build {{build.number}}
       {{else}}
         🛑 failed for 👷‍♂️ build {{build.number}}
       {{/success}}
   when:
     status:
       - failure
       - success
   depends_on:
     - deploy2nomad
   

