kind: pipeline
type: exec
name: default
workspace:
  path: /drone/src
steps:
- name: Deploy2nomad
  environment:
    SERVICE_NAME:
      from_secret: SERVICE_NAME
    APPLICATION_NAME:
      from_secret: APPLICATION_NAME
    SERVICE_VERSION:
      from_secret: SERVICE_VERSION
    SERVICE_PORT:
      from_secret: SERVICE_PORT
    NOMAD_IP:
      from_secret: NOMAD_IP
  commands:
  - pwd
  - export NOMAD_ADDR="http://$NOMAD_IP:4646"
  - j2 /drone/src/srv-template.nomad > $SERVICE_NAME-$APPLICATION_NAME.nomad
  - nomad job run $SERVICE_NAME-$APPLICATION_NAME.nomad
  
---
kind: pipeline
type: docker
name: Notify
steps:
 - name: notification
   image: appleboy/drone-telegram
   settings:
     token:
       from_secret: TELEGRAM_TOKEN
     to: 
       from_secret: TELEGRAM_ID
     message: >
       📝 {{repo.name}} / {{commit.branch}} - {{commit.message}}
       {{#success build.status}}
         ✅ succeeded  for 👷‍♂️ build {{build.number}}
       {{else}}
         🛑 failed for 👷‍♂️ build {{build.number}}
       {{/success}}
   when:
     status:
       - failure
       - success
   

