definitions:
- &DOCKER_SETTINGS 
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD

# https://cogarius.medium.com/1-3-complete-guide-to-ci-cd-pipelines-with-drone-io-a53daaf28cf6
kind: pipeline
type: docker
name: Push on Docker HUB

steps:

 - name: publish 
   image: plugins/docker
   #environment:
   #  SWARM_MODULE_VERSION: blabla
   #  SWARM_MODULE_NAME: blabla
   settings:
     context: .
     repo: 
       from_secret: ${APPLICATION_NAME}/${SERVICE_NAME}
     dockerfile: Dockerfile #./setup/Dockerfile
     <<: *DOCKER_SETTINGS
     #build_args_from_env:
     #- SWARM_MODULE_VERSION
     #- SWARM_MODULE_NAME
     tag:
     - latest  
     - ${DRONE_TAG} #${DRONE_BUILD_NUMBER}
   when:
     branch:
     - production
     - main

#depends_on:
#  - deploy2nomad
   

